### ISSUE TITLE
Finne en bedre datakilde for kontorsøket

### ISSUE THREAD

**Issue by ojnybo** [navikt/tilbakemeldinger#278]
- [x]  Ta kontakt med NORG og team Register for å flytte informasjon til deres registre slik at vi kan oppdatere basert på alerts v/Aksel (Anne Worren)
- [ ]  ny løsning for datagrunnlaget (API)

https://jira.adeo.no/browse/FAGSYSTEM-151598

**Comment by ojnybo** [comment]
Tips fra Sindre Joheim: 

> Hei, jeg så du var nevnt ifm med https://jira.adeo.no/browse/FAGSYSTEM-173967 og ville tipse om et mulig alternativ. Inntil PDL får en tjeneste som leverer geografisk "område" (ikke tilknytning til ident) eller på annen måte tilbyr noe som passer, kan dere eventuelt se på oppslag i TPS via https://confluence.adeo.no/display/FEL/TPSWS+-+Tjeneste+REST+adressesoek og deretter kall til NORG for å finne rett NAV-enhet.
> Søket gir en geografisk referanse tilsvarende GT basert på som om en levende person bodde på adressen. Dvs det er brukt samme begrep i tjenesten selv om det ikke er noen ident knyttet til GT-en. Digisos har brukt tjenesten en stund fra deres NAV-sider vet jeg.

**Comment by ojnybo** [comment]
Dette bør gjøres utenfor `tilbakemeldinger`-appen, da denne skal rendyrkes og overtas av Team Søknad

**Comment by anders-nom** [comment]
Har begynt på en backend-app for kontorsøk: https://github.com/navikt/nav-office-search-api
Gjenstår noe jobb, men kombinasjonen TPS adressesøk, SSBs lister over kommunenr/bydelsnr og Postens postnr-register gir oss alt vi trenger for å hente ut kontorer fra norg2.
