### ISSUE TITLE
Flytte forsiden for tilbakemeldinger til XP

### ISSUE THREAD

**Issue by anders-nom** [navikt/tilbakemeldinger#5]
https://www.nav.no/person/kontakt-oss/nb/tilbakemeldinger/

Er ingen spesiell grunn til at denne siden trenger å ligge i tilbakemeldinger-appen. Hadde kanskje vært fint å flytte denne til XP for enklere å kunne gjøre redaksjonelle endringer på siden, og for å få likt design som de andre kontakt-oss sidene.

**Comment by eivindskifjeld** [comment]
Tas opp på Monday commit
