### ISSUE TITLE
Skrive om appen til et mer effektivt rammeverk (vite+preact?)

### ISSUE THREAD

**Issue by anders-nom** [navikt/tilbakemeldinger#608]
Veldig mye javascript her, og kun client-side rendering. Kunne vi migrert til noe mer lean? 😄

**Comment by macbruker** [comment]
Har hørt og lest mye bra om [Remix](https://remix.run/).

**Comment by PerOlavM** [comment]
Samtidig bør vi:
- Rydde opp i div-helvetet!
- Less -> Sass modules
- Bruke Designsystemet bedre (knapper, ikoner, ...)

**Comment by bdahle** [comment]
- [ ] Fjerne core-js? Importeres for å støtte gammel IE? 200k js?

**Comment by bdahle** [comment]
- [ ] Oppgrader til Vite 5
