### ISSUE TITLE
Rydde i html/css

### ISSUE THREAD

**Issue by bdahle** [navikt/tilbakemeldinger#665]

**Comment by bdahle** [comment]
https://github.com/navikt/tilbakemeldinger/issues/608#issuecomment-1439652478:

- [ ] Rydde opp i div-helvetet!
- [ ] Less -> Sass modules
- [ ] Bruke Designsystemet bedre (knapper, ikoner, ...)

**Comment by PerOlavM** [comment]
Vurdere DS sin ComboBox (Beta). 
ARC Toolkit rapporterer flere feil med dagens ComboBox (som er fra downshift).
